# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: winglau14 github
url: http://winglau14.github.io
feed: /atom.xml
author_info: <a href="http://winglau14.github.io/">winglau14</a>

myblog:
  gavatar: images/2.jpg
  gpname: winglau14
  github: https://github.com/winglau14
  email: mailto:397069329@qq.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
